#!/usr/bin/env bash
# A Bash script that prints information about a domain and it's subdomain(s).

display_info ()
{
    domain="$1"
    subdomain="$2"
    record=$(dig "$sub_d.$domain" | awk '/ANSWER SECTION/ { getline; print $4 }')
	dest=$(dig "$sub_d.$domain" | awk '/ANSWER SECTION/ { getline; print $5 }')
	echo "The subdomain $sub_d is a $record record and points to $dest"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
	display_info "$1" "$subdomain"
    fi
done
