#!/usr/bin/env bash
# bash script that transfers a file from a client to a server using scp
if [[ $# -gt 3 ]]
then
    source_f=$1
    dest_ip=$2
    username=$3
    key_path=$4

    scp -i "$key_path" -o StrictHostKeyChecking=no "$source_f" "$username@$dest_ip:~/"
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
