#!/usr/bin/env bash
# Update package index
sudo apt update

# Install Nginx
sudo apt install nginx

# Allow traffic on port 80
sudo ufw allow 'Nginx HTTP'

# Create an Nginx configuration file
echo "
server {
    listen 80;
    server_name _;

    location / {
        return 200 \"Hello World!\";
    }
}
" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
sudo service nginx restart
