#!/usr/bin/env bash
# A bash script that:

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo chown  "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
