#!/usr/bin/env bash
# Configure Nginx server

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.nginx-debian.html

URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"


sudo service nginx restart
